#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset


CERR='\033[0;31m'
NC='\033[0m'


container=docker
command -v "podman" &>/dev/null && container=podman


# Try to ask for linting. If tty cannot be opened the git command might be issued from a GUI. In this case, ignore the hook.
read -r -n1 -t 1 -p "babellint this? [b/f/*]: " c < /dev/tty || exit 0
echo


function fail {
    echo -e "\\n\\n${CERR}Sorry, but a pre-commit-hock has prevented this commit.${NC}"
    echo -e "You may ignore the hock via\\n"
    echo -e "\\t git commit -n \\t\\t"
    exit 1
}
trap fail ERR




c=${c:-b}
case "$c" in
    "f")
        /usr/local/bin/$container run --rm --interactive -e "TERM=xterm-256color" -v "$(pwd)":"$(pwd)" -w "$(pwd)" heussd/babellint:latest "--fix"
        ;;
    "#")
        exit 0
	;;
    *)
        /usr/local/bin/$container run --rm --interactive -e "TERM=xterm-256color" -v "$(pwd)":"$(pwd)" -w "$(pwd)" heussd/babellint:latest
        ;;
esac
