tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "azure-cli"
brew "bash-completion"
brew "bat"
brew "brew-cask-completion"
brew "ctop"
brew "dive"
brew "figlet"
brew "fzf"
brew "graphviz"
brew "htop"
brew "mas"
brew "maven"
brew "offlineimap"
brew "p7zip"
brew "pandoc"
brew "ripgrep"
brew "stow"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "unrar"
brew "wget"
brew "z"
cask "appcleaner"
cask "betterzip"
cask "cryptomator"
cask "cyberduck"
cask "db-browser-for-sqlite"
cask "docker"
cask "dozer"
cask "dupeguru"
cask "easy-move-plus-resize"
cask "firefox"
cask "font-jetbrains-mono"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "gimp"
cask "go2shell"
cask "handbrake"
cask "imageoptim"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keka"
cask "knockknock"
cask "macdown"
cask "mactex"
cask "macvim"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "r"
cask "retinizer"
cask "sourcetree"
cask "suspicious-package"
cask "tiles"
cask "tor-browser"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "webpquicklook"
cask "yed"
cask "zazu"
mas "CotEditor", id: 1024640650
mas "Disk Graph", id: 697942581
mas "Flycut", id: 442160987
mas "Keynote", id: 409183694
mas "Next Meeting", id: 1017470484
mas "Numbers", id: 409203825
mas "OTP Manager", id: 928941247
mas "Pages", id: 409201541
mas "SleepTime", id: 465772885
mas "Theine", id: 955848755
mas "Xcode", id: 497799835
