# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

default: true

MD012: # Consecutive blank lines
  maximum: 2

# MD013/line-length - Line length
MD013: false

MD022: # Headings should be surrounded by blank lines
  lines_above: 1

MD041: false # First line in a file should be a top-level heading

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: true
