#!/bin/bash

OS=`uname -s | sed -e 's/  */-/g;y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'`
bashrc="$(dirname "${BASH_SOURCE[0]}")/bashrc"

# Add custom bashrc to user config
if [[ ! ` cat ~/.bashrc | grep "[[ -e $bashrc ]] && source $bashrc" ` ]]; then
  echo "" >> ~/.bashrc
  echo "[[ -e $bashrc ]] && source $bashrc" >> ~/.bashrc
fi

case "$OS" in
  "darwin")
    echo "Autohide dock"
    defaults write com.apple.dock orientation -string bottom
    defaults write com.apple.dock autohide -boolean true

    # http://www.macbug.de/2012/01/23/os-x-automatisches-aus-und-einblenden-des-docks-beschleunigen/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Macbug+%28MacBug.de%29
    echo "Faster auto hide"
    #defaults write com.apple.dock autohide-time-modifier -int 0
    defaults write com.apple.dock autohide-time-modifier -float 0.1
    #defaults delete com.apple.dock autohide-time-modifier

    echo "Do not dim hidden applications"
    defaults write com.apple.dock showhidden -boolean false

    echo "Set dock size"
    defaults write com.apple.dock tilesize -integer 50
    defaults write com.apple.Dock size-immutable -bool yes
    defaults write com.apple.Dock contents-immutable -bool no 

    # http://www.cultofmac.com/155992/view-stacks-more-useful-list-view/
    echo "Enable a more useful list view"
    defaults write com.apple.dock use-new-list-stack -bool YES
    
    echo "Hide Library"
    # SetFile -a V ~/Library
    chflags hidden ~/Library/

    echo "Disable the Crash Dialog Box"
    defaults write com.apple.CrashReporter DialogType none

    echo "Disable Terminal mouse over"
    defaults write com.apple.Terminal FocusFollowsMouse -string NO

    # http://www.macosxtips.co.uk/index_files/terminal-commands-for-hidden-settings-in-snow-leopard.php
    echo "Enable Text Substitutions"
    defaults write -g WebAutomaticTextReplacementEnabled -bool true
    defaults write -g WebAutomaticDashSubstitutionEnabled -bool true
    defaults write -g WebContinuousSpellCheckingEnabled -bool true


    # https://gist.github.com/2260182

    echo "Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)"
    defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

    echo "Enable subpixel font rendering on non-Apple LCDs"
    defaults write NSGlobalDomain AppleFontSmoothing -int 2

    #echo "Enable the 2D Dock"
    #defaults write com.apple.dock no-glass -bool true

    echo "Enable iTunes track notifications in the Dock"
    defaults write com.apple.dock itunes-notifications -bool true

    echo "Enable menu bar transparency"
    defaults write NSGlobalDomain AppleEnableMenuBarTransparency -bool true

    echo "Set battery menu bar item"
    defaults write com.apple.menuextra.battery ShowPercent -string "NO"
    defaults write com.apple.menuextra.battery ShowTime -string "NO"

    echo "Allow quitting Finder via ⌘ + Q; doing so will also hide desktop icons"
    defaults write com.apple.finder QuitMenuItem -bool true

    #echo "Show all filename extensions in Finder"
    #defaults write NSGlobalDomain AppleShowAllExtensions -bool true

    echo "Use current directory as default search scope in Finder"
    defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

    echo "Show Path bar in Finder"
    defaults write com.apple.finder ShowPathbar -bool true

    echo "Show Status bar in Finder"
    defaults write com.apple.finder ShowStatusBar -bool true

    echo "Expand save panel by default"
    defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

    echo "Expand print panel by default"
    defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

    echo "Enable AirDrop over Ethernet and on unsupported Macs running Lion"
    defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

    echo "Automatically open a new Finder window when a volume is mounted"
    defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
    defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
    defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

    echo "Display full POSIX path as Finder window title"
    defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

    #echo "Avoid creating .DS_Store files on network volumes"
    #defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

    echo "Disable the warning when changing a file extension"
    defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

    echo "Show item info below desktop icons"
    /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist

    echo "Disable the warning before emptying the Trash"
    defaults write com.apple.finder WarnOnEmptyTrash -bool false

    # Empty Trash securely by default
    # defaults write com.apple.finder EmptyTrashSecurely -bool true

    echo "Set password delay"
    defaults write com.apple.screensaver askForPassword -int 1
    defaults write com.apple.screensaver askForPasswordDelay -int 5

    echo "Enable tap to click (Trackpad)"
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true

    echo "Map bottom right Trackpad corner to right-click"
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true

    echo "Enable Safari’s debug menu"
    defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

    echo "Make Safari’s search banners default to Contains instead of Starts With"
    defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

    echo "Add a context menu item for showing the Web Inspector in web views"
    defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

    echo "Only use UTF-8 in Terminal.app"
    defaults write com.apple.terminal StringEncodings -array 4

    echo "Disable the Ping sidebar in iTunes"
    defaults write com.apple.iTunes disablePingSidebar -bool true

    echo "Disable all the other Ping stuff in iTunes"
    defaults write com.apple.iTunes disablePing -bool true

    echo "Make ⌘ + F focus the search input in iTunes"
    defaults write com.apple.iTunes NSUserKeyEquivalents -dict-add "Target Search Field" "@F"

    # Disable send and reply animations in Mail.app
    # defaults write com.apple.Mail DisableReplyAnimations -bool true
    # defaults write com.apple.Mail DisableSendAnimations -bool true

    # Disable Resume system-wide
    # defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -bool false

    #echo "Reset Launchpad"
    #[ -e ~/Library/Application\ Support/Dock/*.db ] && rm ~/Library/Application\ Support/Dock/*.db


    # https://github.com/j2fly/babushka-deps/blob/master/osx.rb

    echo 'Show these items on the desktop'
    defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
    defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
    defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
    defaults write com.apple.finder ShowMountedServersOnDesktop -bool true

    echo 'finder view options'
    /usr/libexec/PlistBuddy -c "Set ':DesktopViewSettings:IconViewSettings:arrangeBy' dateModified" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set ':DesktopViewSettings:IconViewSettings:gridSpacing' 100" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set ':DesktopViewSettings:IconViewSettings:iconSize' 128" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set ':DesktopViewSettings:IconViewSettings:labelOnBottom' true" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set ':DesktopViewSettings:IconViewSettings:showItemInfo' true" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set ':DesktopViewSettings:IconViewSettings:showIconPreview' true" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set ':DesktopViewSettings:IconViewSettings:textSize' 12" ~/Library/Preferences/com.apple.finder.plist


    echo "Kill affected applications"
    for app in Safari Finder Dock Mail SystemUIServer; do killall "$app" >/dev/null 2>&1; done

    # Browse to basic software
    open http://www.google.de/chrome/
    open http://appdrive.net/mediathek/
    
    ;;
  "linux")
    echo "This is linux!"
    ;;
  default)
    echo "unsupported os!"
    exit
esac

source $bashrc
