tap "buo/cask-upgrade"
tap "beeftornado/rmtree"
tap "dteoh/sqa"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "bash-completion"
brew "brew-cask-completion"
brew "figlet"
brew "graphviz"
brew "htop"
brew "mackup"
brew "mas"
brew "maven"
brew "offlineimap"
brew "p7zip"
brew "pandoc"
brew "stow"
brew "terminal-notifier"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "unrar"
brew "wget"
brew "z"
cask "appcleaner"
cask "atom"
cask "battle-net"
cask "betterzip"
cask "betterzipql"
cask "cronnix"
cask "cryptomator"
cask "cyberduck"
cask "dupeguru"
cask "easy-move-plus-resize"
cask "eclipse-java"
cask "firefox"
cask "font-source-code-pro"
cask "freeplane"
cask "gimp"
cask "go2shell"
cask "handbrake"
cask "imageoptim"
cask "iterm2"
cask "keka"
cask "macdown"
cask "mactex"
cask "macvim"
cask "mediathekview"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "retinizer"
cask "rssowl"
cask "skim"
cask "sourcetree"
cask "spotify"
cask "sqlitebrowser"
cask "suspicious-package"
cask "torbrowser"
cask "transmission"
cask "vlc"
cask "webpquicklook"
cask "yed"
cask "zazu"
cask "dteoh/sqa/slowquitapps"
mas "CotEditor", id: 1024640650
mas "Disk Graph", id: 697942581
mas "Flycut", id: 442160987
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LibreOffice Vanilla", id: 921923693
mas "Next Meeting", id: 1017470484
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "OTP Manager", id: 928941247
mas "Pages", id: 409201541
mas "SleepTime", id: 465772885
mas "Theine", id: 955848755
mas "Xcode", id: 497799835
