#!/bin/bash

function gitfetchresetmodules() {
	git fetch --all
	git reset --hard origin/master
	git submodule update --recursive --remote --init
}

# Find the .dotfiles root folder where this script is located at, taken from https://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"


STOW_DIR=$DIR

pushd $STOW_DIR

gitfetchresetmodules
#source "`uname -s`.md"
#./stow-dotfiles [^_]*/


if [ -d ~/.scripts ]; then
	cd ~/.scripts
	gitfetchresetmodules
fi

popd
