#!/usr/bin/perl

use XML::RSS;
use Unicode::MapUTF8 qw(to_utf8);
use strict;

sub wget() {
	my $file = $_[0];
	
	# Toogles get-method: http vs local
	if($file =~ /http:\/\//) {
		use LWP::UserAgent;
		
		my $userAgent = LWP::UserAgent->new();
		$userAgent->agent('obPodcast0r');

		my $request = HTTP::Request->new('GET', $file);
		my $response = $userAgent->request($request);

		if ( $response->is_error() ) {
			print ("ERROR code was " . $response->code() . ", " . $response->message());
		}
		
		return ($response->content());
	}
	else {
		open(FILE, $file) or print "ERROR File not found: $file";
		my ($line, $string);
		while($line = <FILE>) {
			$string .= $line;
		}
		close(FILE);
		return $string;
	}
}

my $podcast = new XML::RSS;
$podcast->parse(&wget($ARGV[0]));

print "<openbox_pipe_menu>\n";

for my $i (sort @{$podcast->{items}}) {
	print "<item label=\"" . to_utf8({ -string => $i->{title}, -charset => 'ISO-8859-1'}) . "\">\n";
	print "<action name=\"Execute\"><command>\n";
	print "urxvt -e obPodcast0rHelper $i->{enclosure}{'url'}\n";
	print "</command></action></item>\n";
	#print $i->{pubDate} . "\n";
}


print "</openbox_pipe_menu>\n";
