#!/bin/bash

# Set intitial field separator
IFS=$'\n'

makeItem() {
	label=$1
	echo '<item label="'$label'">'
	echo '<action name="Execute"><command>'
	echo '<startupnotify><enabled>yes</enabled></startupnotify>'
	echo $2
	echo '</command></action>'
	echo '</item>'
}

echo "<openbox_pipe_menu>"
for i in `ls -B ~/.VirtualBox/Machines/ -St`; do
	makeItem $i "VBoxManage startvm $i"
done
echo "</openbox_pipe_menu>"
