#!/bin/sh

SERVICE="http://localhost:55000/"

url="$1"

curl --fail "$SERVICE/extract.php?url=$url" | jq -r ".content" | w3m -T text/html

#curl --fail --silent "http://maya.local:8080/extract.php?url=$url" | jq -r ".content" | w3m -v -F -T text/html

# Requires npm install -g mozilla-readability-cli
#curl --fail --silent "$url" | readability "$url" | w3m -T text/html -o confirm_qq=false 

