#!/bin/sh

SERVICE="http://localhost:55000/"

if curl --fail --silent "$SERVICE" -o /dev/null; then
	curl --fail "$SERVICE/makefulltextfeed.php?max=200&links=preserve&url=$*"
else
	curl --fail "$*"
fi
