#!/bin/bash
# Retrieves image URLs, displays images at max. scale via kitty's icat
# by Timm Heuss - CC-BY 4.0 
#
# Designed to display individual images from feeds like xkcd.com.
#
# Usage:
# 1) Define a new macro in your config:
#    macro i set pager "$PATHTOTHIS/img-pager"; open; set pager internal
# 2) Now you use this pager in articleview using the hotkey <comma>+<i>

set -o errexit
set -o pipefail
set -o nounset


image=$(grep -E -o "https?://[a-zA-Z0-9./?=_%:-]*" < "${1}" | tail -1)

# Detect terminal dimensions
dims="$(tput cols)x$(tput lines)@0x0" 

clear
kitty +kitten icat --clear
kitty +kitten icat --hold --scale-up --place "$dims" "$image"
clear
