#!/bin/sh

url="$1"
title="$2"
title=$(echo "$title" | sed -e 's/ (matches.*$//') 

if [ -e "$title" ]; then
	title=$(curl --fail --silent "http://maya.local:8080/extract.php?url=$url" | jq -r ".title" )
fi

description=$(curl --fail --silent "http://maya.local:8080/extract.php?url=$url" | jq -r ".excerpt")
# feed="$4"

file=$(date '+%Y-%m-%d')

cd "$TH_PROJECTS_FOLDER/vimwiki" || exit 1

echo "

## $title 

> $description

<$url>
(Last access $(date '+%Y-%m-%d'))" >> ./"$file.md"


git add "$file.md"
git commit -m "$file.md (auto commit)" -n > /dev/null

exit 0
