#!/bin/bash
# bash required for echo -n

# Checks if at least one of the given hosts is pingable. Returns true if that's the case. 

onlineHosts=0

for host in $*; do
	echo -n "Host $host..."
	ping -c 1 $host &> /dev/null && let onlineHosts=onlineHosts+1 && echo " is online" && continue
	echo " is offline"
done

echo "$onlineHosts/$# hosts were online"

if [ $onlineHosts -gt 0 ]; then
	exit 1
else
	exit 0
fi
