#!/bin/sh

sudo softwareupdate -i -a

brew update
brew upgrade -all
brew cleanup -s
rm -rf $(brew --cache)

npm install npm -g
npm update -g

sudo gem update --system
sudo gem update
sudo gem cleanup
