#!/bin/sh

sudo softwareupdate -i -a

brew update
brew upgrade -all
brew cu --yes --cleanup
brew cleanup -s
rm -rf $(brew --cache)

npm install npm -g
npm update -g

sudo gem update --system
sudo gem update
sudo gem cleanup

python -m pip install --upgrade pip
python3 -m pip install --upgrade pip
