#!/bin/sh
# Backup essential Firefox profile files

# Source for filenames: https://support.mozilla.org/de/kb/benutzerprofile-mit-ihren-persoenlichen-daten

TARGET=$1
[ -z $TARGET ] && TARGET="thunderbird-backup-profiles.7z"

FF_PROFILE="$HOME/Library/Thunderbird/"

INCLUDED_FILES=""

# Local Mail Archive
INCLUDED_FILES="$INCLUDED_FILES -ir\!$FF_PROFILE/Mail/"

# Bookmarks + History
INCLUDED_FILES="$INCLUDED_FILES -ir\!$FF_PROFILE/places.sqlite"
INCLUDED_FILES="$INCLUDED_FILES -ir\!$FF_PROFILE/favicons.sqlite"

# Passwords
INCLUDED_FILES="$INCLUDED_FILES -ir\!$FF_PROFILE/key*.db"
INCLUDED_FILES="$INCLUDED_FILES -ir\!$FF_PROFILE/logins.json"

# Site-specific permissions
INCLUDED_FILES="$INCLUDED_FILES -ir\!$FF_PROFILE/permissions.sqlite"
INCLUDED_FILES="$INCLUDED_FILES -ir\!$FF_PROFILE/content-prefs.sqlite"

# Search engines
INCLUDED_FILES="$INCLUDED_FILES -ir\!$FF_PROFILE/search.json.mozlz4"

# Personal dictionary
INCLUDED_FILES="$INCLUDED_FILES -ir\!$FF_PROFILE/persdict.dat"

# Form history
INCLUDED_FILES="$INCLUDED_FILES -ir\!$FF_PROFILE/formhistory.sqlite"


eval "7z u -mx9 -ms=off $TARGET $INCLUDED_FILES"
