#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

if [ ! -d ".git" ]; then
    git init
fi

repository=${PWD##*/}

open -a SourceTree -W --args "$PWD"

gh repo create "$repository" --private

git remote add origin "git@github.com:heussd/$repository.git" 
git push --set-upstream origin main --no-verify
