#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

url=$(git config --get remote.origin.url)
repository=${PWD##*/}

pushd ~/projects/github-git-of-gits

git pull
git submodule add "$url"
git commit -a -m "Add $repository"

popd