#!/bin/bash
PROCESS=MeetingBar
number="$(pgrep $PROCESS)"

# https://gist.github.com/kaleksandrov/3cfee92845a403da995e7e44ba771183
quitvpn() {
	launchctl remove com.paloaltonetworks.gp.pangps
        launchctl remove com.paloaltonetworks.gp.pangpa
}
startvpn() {
	launchctl load /Library/LaunchAgents/com.paloaltonetworks.gp.pangpa.plist
    	launchctl load /Library/LaunchAgents/com.paloaltonetworks.gp.pangps.plist
}


declare -a workapps=(
	"Google Chrome"
	"Google Drive"
   	"Clockify Desktop"
   	"Dozer"
   	"KerberosMenuExtra"
   	"MeetingBar"
   	"Slack"
   	"Microsoft Teams"
)
declare -a workapps_ko=(
	"Microsoft Azure Storage Explorer"
	"Microsoft Edge"
	"Visual Studio Code"
	"Teams" // No "MS" prefix to kill...
)

declare -a nonworkapps=(
	"Mail"
   	"Calendar"
)


if [[ "$number" -gt 0 ]]; then
    echo "Afterwork mode"
    gita sync &
    quitvpn

    for app in "${workapps[@]}"; do killall "$app" || true; done
    for app in "${workapps_ko[@]}"; do killall "$app" || true; done
    for app in "${nonworkapps[@]}"; do open --background -a "$app"; done
else
    echo "Work mode"
    
    for app in "${nonworkapps[@]}"; do killall "$app"; done

    gita sync
    startvpn

    for app in "${workapps[@]}"; do open --background -a "$app"; done
fi


