#!/bin/bash
PROCESS=MeetingBar
number="$(pgrep $PROCESS)"

# https://github.com/orbxball/make-Pulse-Secure-great-again
quitvpn() {
  launchctl unload -w /Library/LaunchAgents/net.pulsesecure.pulsetray.plist
  osascript -e 'tell application "Pulse Secure" to quit'
}
startvpn() {
  launchctl load -w /Library/LaunchAgents/net.pulsesecure.pulsetray.plist
}


declare -a workapps=(
	"Google Chrome"
	"Google Drive"
   	"Clockify Desktop"
   	"Dozer"
   	"KerberosMenuExtra"
   	"MeetingBar"
    	"Microsoft Edge"
)

declare -a nonworkapps=(
	"Maestral"
	"Mail"
   	"Calendar"
)


if [ "$number" -gt 0 ]; then
    echo "Afterwork mode"
    gita sync &
    quitvpn

    for app in "${workapps[@]}"; do killall "$app"; done
    for app in "${nonworkapps[@]}"; do open --background -a "$app"; done
else
    echo "Work mode"
    
    for app in "${nonworkapps[@]}"; do killall "$app"; done

    gita sync
    startvpn

    for app in "${workapps[@]}"; do open --background -a "$app"; done
fi


