#!/bin/bash

# Parse command line arguments
FORCE=false
while [[ $# -gt 0 ]]; do
	case $1 in
		-f|--force)
			FORCE=true
			shift
			;;
		*)
			shift
			;;
	esac
done

AWESOME=$TH_PROJECTS_FOLDER/awesome-templates/

template=$(find "$AWESOME" \
	-maxdepth 1 \
	-not -path '*/.*' \
	-not -path '*/' \
	| fzf)

if [ -n "$template" ]; then
	if [ "$FORCE" = true ]; then
		cp -Rv "$template"/. .
	else
		cp -Rv -n "$template"/. .
	fi
fi

