#!/bin/bash


cc='docker'

# Find the right container cli
command -v "podman" >/dev/null 2>&1 && {
	cc='podman'
}
command -v "lima" >/dev/null 2>&1 && {
	cc='lima nerdctl'
}

function color() {
	cols=$(tput cols)
	words=${#3}
	cols=$((cols - words - 2))
	cols=$((cols / 2 ))
	
	printf "\\n"
	printf "\\e[1;%sm" "$1" # foreground color
	printf "\\e[1;%sm" "$2" # background color
	for ((i=0; i<= cols; i++)); do printf " "; done
	printf "%s" "$3"
	for ((i=0; i<= cols; i++)); do printf " "; done
	printf "\\e[0m\\n"
	printf "\\n"
}

function fail() {
	color 30 41 "There are linter issues :-("
	read -r
	exit 1
}

trap fail ERR


dockerrun() { eval "$cc" run --rm --interactive --tty "$*"; }
dockerrunu() { eval dockerrun --user="$(id -u):$(id -g)" "$*"; }
dockerrunuw() { eval dockerrunu --volume "$(pwd)":"$(pwd)" --workdir "$(pwd)" "$*"; }

dockerrunuw ghcr.io/heussd/babellint:main

trap - ERR
color 30 42 "All OK"
read -r -t2
