#!/bin/bash


cc='docker'

# Find the right container cli
command -v "podman" >/dev/null 2>&1 && {
	cc='podman'
}
command -v "lima" >/dev/null 2>&1 && {
	cc='lima nerdctl'
}

function fail() {
	echo "There are linter issues :-("
	read -r
}
trap fail ERR


dockerrun() { eval "$cc" run --rm --interactive --tty "$*"; }
dockerrunu() { eval dockerrun --user="$(id -u):$(id -g)" "$*"; }
dockerrunuw() { eval dockerrunu --volume "$(pwd)":"$(pwd)" --workdir "$(pwd)" "$*"; }

dockerrunuw ghcr.io/heussd/babellint:main

trap - ERR
read -r -t3
