#!/bin/bash

# Bridge for Podman / Docker compose

set -o errexit
set -o pipefail
set -o nounset

# Find the right container cli
command -v "podman" >/dev/null 2>&1 && {
	podman-compose "$@"
}
command -v "lima" >/dev/null 2>&1 && {
	cc compose "$@"
}
command -v "docker" >/dev/null 2>&1 && {
	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose
}

