#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

function kittytheme() {
	pushd "$HOME/.config/kitty" || exit 1

	activeTheme="active_mode.conf"
	
	rm "$activeTheme" || true
	ln -s "modes/$1.conf" "$activeTheme"
	
	popd

	for pid in $(pgrep 'kitty'); do
	    kill -SIGUSR1 "$pid"
    	done
}

function wallpaper() {
	osascript -e "tell application \"System Events\" to tell every desktop to set picture to \"/System/Library/Desktop Pictures/Solid Colors/$1.png\""
}



if [ "$(defaults read -g AppleInterfaceStyle | grep 'Dark')" ]; then
	echo "Going white"
	#wallpaper "Silver"
	kittytheme "white"
else
	echo "Going black"
	#wallpaper "Black"
	kittytheme "dark"
fi

osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to not dark mode'


killall -KILL SystemUIServer
killall -KILL Dock
