#!/bin/bash
# Power-cycle local Docker containers

# Terminate if commands fail
#set -e
#set -o pipefail

function checkIfInstalled {
  if [ ! -x "$(command -v $1)" ]; then
      echo -e "$1 is required to launch this script. Install it via: \n\t$2"
      exit 1
  fi
}
function openExposedPorts {
  sleep 3
  for service in $(docker-compose $ymlfiles config | shyaml keys services); do
    port=$(docker-compose $ymlfiles config | shyaml get-value services.$service.ports 2> /dev/null | grep -o -E '[0-9]+' | head -n 1)
    [ ! -z "$port" ] && (
        echo "Opening $service $port..."
        open http://localhost:$port
    )
  done
}
function buildImages {
	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
}
function openMultitail {
  multitailcmd="multitail -M 10000"
  for service in $(docker-compose $ymlfiles config | shyaml keys services); do
    multitailcmd="$multitailcmd -p l -cT ansi -l 'docker-compose logs -f $service; sleep 120000'"
  done
  eval $multitailcmd 
}
function runImages {
	docker-compose $ymlfiles up -d --remove-orphans --timeout 2
	#if [ $? -gt 0 ]; then exit 1; fi
}


checkIfInstalled multitail "brew install multitail"
checkIfInstalled shyaml "pip install shyaml"

buildImages
runImages

openExposedPorts &
openMultitail

docker-compose $ymlfiles down --remove-orphans --timeout 2
#if [ $? -gt 0 ]; then exit 1; fi

exit 0
