#!/bin/bash
# Does what "docker-compose push" is supposed to do but doesn't

function checkIfInstalled {
  if [ ! -x "$(command -v "$1")" ]; then
      echo -e "$1 is required to launch this script. Install it via: \\n\\t$2"
      exit 1
  fi
}

function buildImages {
  echo "Pushing all images..."
  for service in $(docker-compose "$ymlfiles" config | shyaml keys services); do
    image=$(docker-compose "$ymlfiles" config | shyaml get-value "services.$service.image")
    if [ -n "$image" ]; then
    	DOCKER_BUILDKIT=1 docker push "$image"
    fi
  done
}
checkIfInstalled shyaml "pip install shyaml"

# collect .yml files
ymlfiles=""
#for filename in *docker-compose*.yml; do
#    [ -e "$filename" ] || continue
#    ymlfiles="$ymlfiles -f $filename"
#done

buildImages

