#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

git pull

read -r -p "Enter BB password:" secret
echo "$secret"
gh secret set BITBUCKET_PASSWORD -b"${secret}"


mkdir -p .github/workflows/
wget https://raw.githubusercontent.com/heussd/dotfiles/main/.github/workflows/mirror-to-bitbucket.yml \
    --output-document=".github/workflows/mirror-to-bitbucket.yml"


git add ".github/workflows/mirror-to-bitbucket.yml" -f
git commit -m "Enable automatic mirroring to BitBucket"
git push
