#!/bin/bash


for project in $(ls ~/projects); do
	folder="$HOME/projects/$project/.git"

	if [ -d $folder ]; then
		pushd $folder > /dev/null
		git remote -v | grep -v heuss && echo $folder
		popd > /dev/null
	fi
done
