#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

selection=$(gh repo list --limit 1000 | fzf)
repository=$(echo $selection | awk '{print $1}')

gh repo clone $repository

cd "${repository#*/}"

