#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

file="$1"
thedate=$(stat -f "%Sm" -t "%Y-%m-%dT%H:%M:%S" "$file")

git add "$file"
GIT_COMMITTER_DATE="$thedate" git commit --date="$thedate" -m "Auto commit (commit dated based on file modification date)"