#!/bin/sh

# Installs a hook to automatically clean Jupyter Notebooks on commit

command -v nbstripout >/dev/null 2>&1 || { pip install --upgrade nbstripout; }
[[ ! -d .git ]] && echo >&2 "No .git repository found in this folder. Aborting." && exit 1

{ echo '#!/bin/sh' & \
  echo "python3 -m nbstripout *.ipynb"; \
} > .git/hooks/pre-commit 

[[ ! -e .git/hooks/pre-commit ]] && echo "Failed to install hook" && exit 1

echo "Hook installed"
exit 0

