#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset


function fail() {
	read -r
}
trap fail ERR

function gitpush() {
  gitcmd="git"
  if [ "$PWD" = "$HOME" ]; then
    gitcmd="git --git-dir=$HOME/.dotfiles-bare-repo/ --work-tree=$HOME/"
  fi
  gitcmd="$gitcmd push"
  echo "$gitcmd"
  eval "${gitcmd}"
}


gitpush
