#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset


function fail() {
	read
}
trap fail ERR

function gitpull() {
  gitcmd="git"
  if [ "$PWD" = "$HOME" ]; then
    gitcmd="git --git-dir=$HOME/.dotfiles-bare-repo/ --work-tree=$HOME/"
  fi
  gitcmd="$gitcmd pull --tags --recurse-submodules"
  echo $gitcmd
  eval ${gitcmd}
}


gitpull
