#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset


read -rsp 'Keepass password: ' passvar

keepassDb="$(find "$HOME/Documents" -name "*.kdbx")"

entry=$(echo "$passvar" | keepassxc-cli ls -q --recursive --flatten "$keepassDb")
entry=$(echo "$entry" | fzf)
secret=$(echo "$passvar" | keepassxc-cli show -q "$keepassDb" "$entry" --attributes Password --show-protected )

echo -n "$secret"
exit 0
