#!/bin/bash
# shellcheck disable=SC2002

conf="$HOME/.config/kitty/readability.conf"
temp="$TMPDIR/readability.conf"


firstline=$(cat "$conf" | head -n 1)


if [[ "$firstline" == \#* ]]; then
	cat "$conf" | cut -c 2- > "$temp"
else
	cat "$conf" | sed 's/^/#/' > "$temp"
fi

mv "$temp" "$conf"

kill -s USR1 "$(pgrep -a kitty)"
