#!/bin/bash
selection=$(kubectl get pod -A | fzf)

namespace=$(echo $selection | awk '{print $1}')
pod=$(echo $selection | awk '{print $2}')

kubectl config set-context --current --namespace=$namespace
kubectl logs $pod -f 
