#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset


function color() {
	cols=$(tput cols)
	words=${#3}
	cols=$((cols - words - 2))
	cols=$((cols / 2 ))
	
	printf "\\n"
	printf "\\e[1;%sm" "$1" # foreground color
	printf "\\e[1;%sm" "$2" # background color
	for ((i=0; i<= cols; i++)); do printf " "; done
	printf "%s" "$3"
	for ((i=0; i<= cols; i++)); do printf " "; done
	printf "\\e[0m\\n"
	printf "\\n"
}

function fail() {
	color 30 41 "This command failed: ($BASH_COMMAND)"
	read -r
	exit 1
}

trap fail ERR

gitcmd="lazygit"
if [ "$PWD" = "$HOME" ]; then
  gitcmd="lazygit --git-dir=$HOME/.dotfiles-bare-repo/ --work-tree=$HOME/"
fi

eval "${gitcmd}"

