#!/bin/bash

IFS=$'\n'

makeItem() {
	label=$1
	echo '<item label="'$label'">'
	echo '<action name="Execute"><command>'
	echo '<startupnotify><enabled>yes</enabled></startupnotify>'
	echo $2
	echo '</command></action>'
	echo '</item>'
}



echo "<openbox_pipe_menu>"
for i in `tail -n 50 .bash_history | uniq | sort -r `; do
	makeItem "$i" "urxvt -e $i"
done
echo "</openbox_pipe_menu>"
