#!/bin/bash

# Set intitial field separator
IFS=$'\n'

makeMenu() {
	# Is $1 a directory?
	if [ -d $1 ]
	then
		# Create submenu and call myself
		echo '<menu id="'$1'" label="_'`echo ${1##*/}`'" execute="'$0' '"'"$1"'"'">'
		echo "</menu>"
	else
		if [ -x $1 ]; then
			echo '<item label="'${1##*/}'">'
			echo '<action name="Execute"><command>'
			echo '<startupnotify><enabled>yes</enabled></startupnotify>'
			echo "$1"
			echo '</command></action>'
			echo '</item>'
		fi
	fi
}

[ ! -d $1 ] && exit

echo "<openbox_pipe_menu>"
for i in `ls -B $1 -St`; do
	makeMenu $1/$i
done
echo "</openbox_pipe_menu>"
