#!/bin/bash
set -o errexit
set -o pipefail


if [[ -e "$1" ]]; then
	cd "$1" || return
fi
if [ "$PWD" = "$HOME" ]; then
	cd "$TH_PROJECTS_FOLDER" || exit 1
fi
sel=$(find . -maxdepth 1 -print0 | xargs -0 gstat --format '%Y :%y %n' | sort -nr | cut -d: -f2- | fzf | cut -d" " -f 4)

if [ "$sel" = "." ]; then
	open -a Terminal "$(pwd)"
else

	if [[ -f "$sel" ]]; then
		vim "$sel"
	else
		cd "$sel" || exit 1
	fi
	op
fi
