#!/bin/bash
set -o errexit
set -o pipefail


if [[ -e "$1" ]]; then
	cd "$1" || return
fi
if [ "$PWD" = "$HOME" ]; then
	cd "$TH_PROJECTS_FOLDER" || exit 1
fi
sel=$(find . -maxdepth 1 -print0 | xargs -0 gstat --format '%Y :%y %n' | sort -nr | cut -d: -f2- | /usr/local/bin/choose -m -u -n 20 -w 50 -s 20 | cut -d" " -f 4)

if [[ "$sel" = *"-made" ]]; then
	op-choose "$sel"
fi

if [[ "$sel" = "." ]]; then
	kitty @ launch --type=tab --tab-title "$sel" --cwd "$(pwd)"
	open .
	exit
fi

cd "$sel" || exit 1
pwd

function openApp() {
	echo "Opening App $1..."
	open -na "$1" --args "$(pwd)" &
}

[ -d .git ] && (
	stree .
)

[ -f package.json ] && openApp "WebStorm"

[ -f "pom.xml" ] && openApp "IntelliJ IDEA"
[ -f "build.gradle.kts" ] && openApp "IntelliJ IDEA"
[ -f "build.gradle" ] && openApp "IntelliJ IDEA"
[ -f "settings.gradle" ] && openApp "IntelliJ IDEA"

[ -f "requirements.txt" ] && openApp "PyCharm"

op-choose