#!/bin/bash
set -o errexit
set -o pipefail

function openApp() {
	echo "Launching $1"
	open -na "$1" --args "$(pwd)" &
}

[ -d ".devcontainer" ] && devcontainer open

[ -d .git ] && (
	stree . # SourceTree opens new instances when using open
	code .
)

[ -f "package.json" ] && openApp "WebStorm"
[ -f "pom.xml" ] && openApp "IntelliJ IDEA"
[ -f "build.gradle.kts" ] && openApp "IntelliJ IDEA"
[ -f "build.gradle" ] && openApp "IntelliJ IDEA"
[ -f "settings.gradle" ] && openApp "IntelliJ IDEA"
[ -f "requirements.txt" ] && openApp "PyCharm"
[ -f "go.mod" ] && openApp "GoLand"
[ -f "go.work" ] && openApp "GoLand"


read -t1 -r
