#!/bin/bash
playercmd="vlc"
playerparam="--no-fullscreen"
playercmd="mpv"
playerparam="--no-fs"

for i in *; do
	if [[ ! -e "$i" ]]; then
		continue
	fi

	if [[ ! -d $i ]]; then
		echo "$i"
		$playercmd $playerparam "$i" &> /dev/null &

		while :; do
			read -r -n 1 -p "Preview selection: " selection
			echo
			echo "$selection" | grep '[a-z0-9]' > /dev/null && break
		done

		if [[ ! -e $selection ]]; then mkdir "$selection"; fi
		mv -v "$i" "$selection"
		killall -9 $playercmd 2&> /dev/null
	fi
done
