#!/bin/sh
# https://apple.stackexchange.com/questions/144311/reset-safari-from-command-line

mv ~/Library/Safari "$HOME/Desktop/Safari-$(date +%Y%m%d%H%M%S)"; \
	rm -Rf ~/Library/Caches/Apple\ -\ Safari\ -\ Safari\ Extensions\ Gallery; \
	rm -Rf ~/Library/Caches/Metadata/Safari; \
	rm -Rf ~/Library/Caches/com.apple.Safari; \
	rm -Rf ~/Library/Caches/com.apple.WebKit.PluginProcess; \
	rm -Rf ~/Library/Cookies/Cookies.binarycookies; \
	rm -Rf ~/Library/Preferences/Apple\ -\ Safari\ -\ Safari\ Extensions\ Gallery; \
	rm -Rf ~/Library/Preferences/com.apple.Safari.LSSharedFileList.plist; \
	rm -Rf ~/Library/Preferences/com.apple.Safari.RSS.plist; \
	rm -Rf ~/Library/Preferences/com.apple.Safari.plist; \
	rm -Rf ~/Library/Preferences/com.apple.WebFoundation.plist; \
	rm -Rf ~/Library/Preferences/com.apple.WebKit.PluginHost.plist; \
	rm -Rf ~/Library/Preferences/com.apple.WebKit.PluginProcess.plist; \
	rm -Rf ~/Library/PubSub/Database; \
	rm -Rf ~/Library/Saved\ Application\ State/com.apple.Safari.savedState
