#!/bin/sh

find $1 -depth -name ".AppleDouble" -exec rm -Rvf {} \;
find $1 -depth -name ".DS_Store" -exec rm -Rvf {} \;
find $1 -depth -iname "Thumbs.db" -exec rm -Rvf {} \;
find $1 -depth -name "System Volume Information" -exec rm -Rvf {} \;
find $1 -depth -name '$RECYCLE.BIN'# -exec rm -Rvf {} \;