#!/bin/bash
# shellcheck disable=SC2086
set -o errexit
set -o pipefail
set -o nounset

rsync -auipv --progress --safe-links \
    --filter=". $HOME/.rsync-filters/backup" \
    -F \
    --exclude=/* \
    $HOME/ \
    geneva:/tank/
