#!/bin/bash

source=$1
target=$2

mkdir -p "$target"

linkLatest() {
	rm "$target/latest" 2> /dev/null
	latest=$(find . -mindepth 1 -maxdepth 1 -type d -print0 | xargs -0 gstat --format '%Y :%y %n' | sort -nr | cut -d: -f2- | head -n 1 | cut -d' ' -f 4)
	latest=${latest##*/}
	ln -s "$latest" "$target/latest"
}

linkLatest
rsync -avHF --stats --link-dest="/$target/latest/" "$source/" "$target/$(date +%Y-%m-%d-%H-%M-%S)/"
linkLatest
