#!/bin/bash

file=$(cd "$TH_PROJECTS_FOLDER/snippets" && find . \
	 | tail -n +2 | cut -c 3- \
	 | /usr/local/bin/choose -m -u -n 20 -w 50 -s 20)

file="$TH_PROJECTS_FOLDER/snippets/$file"
if [ -e "$file" ]; then
	pbcopy < "$file"
else
	echo "$file not found"
	#searchterm=$(echo $file | sed -e 's/\ /+/g')
	#open "https://www.google.com/search?q=$searchterm"
fi
