#!/bin/bash
PROCESS=MeetingBar
number="$(pgrep $PROCESS)"


declare -a workapps=(
	"Chat"
	"Gmail"
	"Google Calendar"
	"Google Chrome"
	"Google Drive"
	"OneDrive"
   	"Dozer"
   	"MeetingBar"
   	"Microsoft Teams (work or school)"
)
declare -a workapps_ko=(
	"Microsoft Azure Storage Explorer"
	"Microsoft Edge"
	"Teams" // No "MS" prefix to kill...
	"Visual Studio Code"
)

declare -a nonworkapps=(
	"Mail"
	"Signal"
)

launchHidden() (
	echo "$1"
	osascript -e "run app \"$1\""
	osascript -e "tell application \"System Events\" to set visible of application process \"$1\" to false"
)

killApp() (
	osascript -e "quit app \"$1\"" || true;
	killall "$1" || true;
)


if [[ "$number" -gt 0 ]]; then
    echo "Afterwork mode"

    for app in "${workapps[@]}"; do killApp "$app" || true; done
    for app in "${workapps_ko[@]}"; do killApp "$app" || true; done
    for app in "${nonworkapps[@]}"; do launchHidden "$app"; done

    osascript << EOF
set theBool to false
    repeat until theBool
        tell application "System Events" to ¬
            if menu item "Close Window" of ¬
                menu 1 of ¬
                menu bar item "File" of ¬
                menu bar 1 of ¬
                application process "Signal" exists then ¬
                set theBool to true
        delay 0.2
    end repeat
tell application "System Events"
	repeat until visible of process "Signal" is false
		set visible of process "Signal" to false
	end repeat
end tell
EOF
else
    echo "Work mode"
    
    for app in "${nonworkapps[@]}"; do killApp "$app"; done
    for app in "${workapps[@]}"; do launchHidden "$app"; done

    #osascript -e 'tell application "System Events" to set visible of application process "Teams" to false'
fi


