name: Mirror to BitBucket
on: [push]

jobs:
  mirror-to-bitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # <-- clone with complete history
      - name: Push
        uses: heussd/mirror-to-bitbucket-github-action@main
        with:
          password: ${{ secrets.BITBUCKET_PASSWORD }}
