# https://mattorb.com/ci-your-dotfiles-with-github-actions/ 
name: Smoke Test

on: [push]

jobs:
  "macOS":
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Execute make
      run:   |
        # Overwrite Brewfile, we do not need to stress download servers
        echo "brew \"fzf\"" > .Brewfile
        make
  "Ubuntu Linux 20.04":
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Execute make
      run:   |
        make
