# Inspired by https://mattorb.com/ci-your-dotfiles-with-github-actions/
#
name: Smoke Tests

on: [push]

# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
jobs:
  macos-11-0:
    name: macOS
    runs-on: macOS-11.0
    steps:
      -
        name: Onboard
        run: |
          cd $HOME
          pwd

          curl -fsSL https://raw.githubusercontent.com/heussd/dotfiles/master/.onboard.sh | bash

          # It seems that there are many preinstalled brew packages by default
          # Gather these packages so that they are not uninstalled with the next step
          brew bundle dump --file .Brewfile --force

          # Add one package to test auto install
          echo "brew \"fzf\"" >> .Brewfile
          
          # We don't want to execute Docker here, so...
          # Mock docker-compose command and inject it into path
          mkdir -p ~/localbins/
          echo '#!/bin/bash' > ~/localbins/docker-compose
          chmod +x ~/localbins/docker-compose
          export PATH=~/localbins/:$PATH

          # Do not install anything but gita
          # Do particularly NOT install docker-compose, as it
          # would overwrite the mock
          echo "gita" > .pip-global-requirements.txt
          
          ls -la

          # Simulate first shell init
          make -f Makefile

  ubuntu-linux-20-04:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      -
        name: Onboard
        run: |
          cd $HOME
          pwd

          wget -O- https://raw.githubusercontent.com/heussd/dotfiles/master/.onboard.sh | bash

          # Overwrite apt packages file, no need to stress download servers
          echo "fzf" > .apt-packages-base

          # Overwrite docker-compose to conserve bandwidth
          echo -e "services:\n  service:\n    image: alpine" > .docker-cli-images.yml

          ls -la

          # Simulate first shell init
          make -f Makefile
