# https://mattorb.com/ci-your-dotfiles-with-github-actions/ 
name: Smoke Test CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Execute full install
      run:   |
        # Overwrite Brewfile, we do not need to stress download servers
        echo "brew \"fzf\"" > .Brewfile
        make
